### ISSUE TITLE
Commissioner Tools Functionality Request

### ISSUE THREAD

**Issue by dlw5007** [spilchen/yahoo_fantasy_api#19]
I've had really good success using yahoo_fantasy_api for some fantasy football player research. However I'm interested in utilizing it to help automate some mid-season customized rules by dropping/adding players from teams' rosters as the commissioner. I don't think I'm able to do this with the current functions available in YFA, and I am not well versed in API calls so I was hoping one of the dev's of this project could point me in the right direction or provide some sample code to execute commissioner drops and adds from the URI's "https://basketball.fantasysports.yahoo.com/nba/XXXXXX/Y/commishdropplayer" and "https://basketball.fantasysports.yahoo.com/nba/XXXXXX/Y/commishaddplayer"

Thanks!

**Comment by spilchen** [comment]
I'm not aware of any APIs that Yahoo! exposes to perform things as the commissioner.  So I wonder if you can use the regular add/drop as long as you authenticate as the commissioner.  I would have to try this out to confirm.

**Comment by dlw5007** [comment]
Thanks for the reply. I attempted what you suggested and received an error indicating I am not the manager of the selected team, even when signed in with commissioner's credentials (see below). I suspected this would not work since commissioners only have the ability to edit rosters through the "commissioner tools" interface.

Error message:

RuntimeError: b'<?xml version="1.0" encoding="UTF-8"?>\n<error xml:lang="en-us" yahoo:uri="http://fantasysports.yahooapis.com/fantasy/v2/lea
gue/402.l.xxxxxx/transactions" xmlns:yahoo="http://www.yahooapis.com/v1/base.rng" xmlns="http://www.yahooapis.com/v1/base.rng">\n <descripti
on>You are not the manager of this team.</description>\n <detail/>\n</error>'

**Comment by spilchen** [comment]
That's too bad.  Yahoo must have a different set of APIs for doing these commish level actions.  Unfortunately, they don't expose them in their documentation, so I don't know what those are.

**Comment by dlw5007** [comment]
I will try to reach out to the Yahoo dev team to see if anything exists. I saw some examples for accepting/rejecting trades as a commish, but nothing else.

Thanks

**Comment by jzaturensky** [comment]
@dlw5007 did you ever hear back from Yahoo on this?
