### ISSUE TITLE
"position_type" KeyError

### ISSUE THREAD

**Issue by rthawkins** [spilchen/yahoo_fantasy_api#29]
As of today, calls like lg.to_team(x).roster() are failing due to the following error:

in roster(self, week, day)
     93                     plyr["position_type"] = next_item["position_type"]
     94                 else:
---> 95                     plyr["position_type"] = next(it)["position_type"]
     96                 plyr["eligible_positions"] = _compact_eligible_pos(next(it))
     97                 plyr["selected_position"] = _compact_selected_pos(next(it))

KeyError: 'position_type'

**Comment by spilchen** [comment]
I just fixed this in fc73c4169081.  Also reflected in version 2.5.1 of the pypi package.
