### ISSUE TITLE
Team - Change Position Function Error

### ISSUE THREAD

**Issue by douglasmonsky** [spilchen/yahoo_fantasy_api#34]
No matter what input I try for date (using datetime.date) variable, it gives me this error "You cannot make changes to your roster for this date.". Also, is it not possible to just do the change immediately instead of at some future date?

**Comment by douglasmonsky** [comment]
Looks like they changed date to week for NFL 

<?xml version="1.0"?>
<fantasy_content>
  <roster>
    <coverage_type>week</coverage_type>
    <week>13</week>

    <players>
      <player>
        <player_key>242.p.8332</player_key>
        <position>WR</position>
      </player>
      <player>
        <player_key>242.p.1423</player_key>
        <position>BN</position>
      </player>
    </players>
  </roster>
</fantasy_content>


https://developer.yahoo.com/fantasysports/guide/

**Comment by noahlibby17** [comment]
I just submitted PR #35 to add support for NFL weeks. Until it's merged feel free to check out my fork of this repo that has week support: https://github.com/noahlibby17/yahoo_fantasy_api
