### ISSUE TITLE
question.  is there a way to retrieve player stats with the api?

### ISSUE THREAD

**Issue by craigham** [spilchen/yahoo_fantasy_api#7]
I am using it for hockey, but is there a way for me to get last 7 day or 14 day stats for a particular player?

thanks,
Craig

**Comment by spilchen** [comment]
No, unfortunately there is no way to get stats for players at the moment.

**Comment by craigham** [comment]
I am able to get some stats by using this in the url:

"league/{}/players;sort=AR;status=FA/stats;type=lastweek"

Have you figured out if all the player stats are available via the api that can be seen within the web site?  Or was there a way to query for valid values for filters?  

The documentation seems woefully out of date, so it is hard to trust what is there reflects what is actually available.

For example yahoo can show standard deviation for last 7 days....but in reading the API Documentation type just supports lastweek, lastmonth, season.  

maybe using beautiful soup and scraping the web app is the way to go.

**Comment by uberfastman** [comment]
@craigham you can get player stats for specific dates, which would let you aggregate stats across, say, an entire week if you want to. If you look at the documentation for the Roster resource [here](https://developer.yahoo.com/fantasysports/guide/roster-resource.html), you can see how to do that. And getting those stats for individual players works the same if you append something like `/stats;type=date;date=2011-05-01` to the end of the request URL to get players.

**Comment by spilchen** [comment]
I added an [api to get the player stats](https://yahoo-fantasy-api.readthedocs.io/en/latest/yahoo_fantasy_api.html#yahoo_fantasy_api.league.League.player_stats).  However, it doesn't provide standard deviation.  It is just a set of stats for a given date range.

```
lg.player_stats([5368,4471,6743,4588], 'lastweek')
[{'player_id': 5368,
  'name': 'Mark Scheifele',
  'position_type': 'P',
  'GP': 3.0,
  'G': 4.0,
  'A': 1.0,
  'PTS': 5.0,
  '+/-': 4.0,
  'PIM': 6.0,
  'PPG': 1.0,
  'PPA': 0.0,
  'PPP': 1.0,
  'GWG': 1.0,
  'SOG': 14.0,
  'S%': 0.286},
 {'player_id': 4471,
  'name': 'Steven Stamkos',
  'position_type': 'P',
  'GP': 4.0,
  'G': 3.0,
  'A': 3.0,
  'PTS': 6.0,
  '+/-': 0.0,
  'PIM': 0.0,
  'PPG': 2.0,
  'PPA': 0.0,
  'PPP': 2.0,
  'GWG': 0.0,
  'SOG': 17.0,
  'S%': 0.176},
 {'player_id': 6743,
  'name': 'Connor McDavid',
  'position_type': 'P',
  'GP': 3.0,
  'G': 0.0,
  'A': 1.0,
  'PTS': 1.0,
  '+/-': -4.0,
  'PIM': 2.0,
  'PPG': 0.0,
  'PPA': 1.0,
  'PPP': 1.0,
  'GWG': 0.0,
  'SOG': 9.0,
  'S%': 0.0},
 {'player_id': 4588,
  'name': 'Braden Holtby',
  'position_type': 'G',
  'GP': 3.0,
  'GS': 3.0,
  'W': 2.0,
  'L': 1.0,
  'GA': 8.0,
  'GAA': 2.68,
  'SA': 91.0,
  'SV': 83.0,
  'SV%': 0.912,
  'SHO': 0.0,
  'MIN': '178:49'}]
```
