### ISSUE TITLE
The path to the binary should be made more generic

### ISSUE THREAD

**Issue by james-stoup** [spilchen/yahoo_fantasy_api#8]
While trying to run your example scripts I ran into an issue in which your scripts weren't seeing the correct version of python on my system. I use PyEnv to manage different versions of python and it was giving it fits. To resolve this you need to change the first line of your example scripts to this:

```#!/usr/bin/env python```

to make it robust enough to handle various environments.

**Comment by spilchen** [comment]
Fixed in bdc3edc
