### ISSUE TITLE
problem with player_stats

### ISSUE THREAD

**Issue by joshuafisher143** [spilchen/yahoo_fantasy_api#9]
I'm having an issue trying to get league player stats to work. I have no issues running other functions from the league class, just player_stats. Any idea why I'm getting this key error?

![player_stats](https://user-images.githubusercontent.com/60308297/73130707-86298380-3fcb-11ea-9be8-7882b111317b.jpg)

**Comment by spilchen** [comment]
What sport is this?  I only tested this with NHL and MLB.

**Comment by joshuafisher143** [comment]
This is for NHL. Player_id 4002 should return stats for Claude Giroux

**Comment by spilchen** [comment]
Hmm, I see Claude when I run the API on my league.  It must be something specific to your league settings.

What is the output of this?
```
lg.yhandler.get_settings_raw(lg.league_id)
```

**Comment by joshuafisher143** [comment]
That correctly outputs the league information and settings. I've even tried running player_stats for another league. Same issue.

**Comment by spilchen** [comment]
I need to see your json output from `get_settings_raw`.  There is something in there that the `player_stats` API doesn't like.

**Comment by joshuafisher143** [comment]
[get_settings_raw_output.txt](https://github.com/spilchen/yahoo_fantasy_api/files/4114315/get_settings_raw_output.txt)

Here you go

**Comment by spilchen** [comment]
Fixed in cc55379

This is in version 1.8.2 of the API
